DROP DATABASE IF EXISTS BRAWLE;
CREATE DATABASE BRAWLE;
USE BRAWLE;

DROP TABLE IF EXISTS LEGENDS_WEAPONS;
DROP TABLE IF EXISTS GAMES_USERS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GAMES;
DROP TABLE IF EXISTS GENDERS;
DROP TABLE IF EXISTS WEAPONS;
DROP TABLE IF EXISTS YEARS;
DROP TABLE IF EXISTS RACES;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS LEGENDS;

CREATE TABLE RACES(
    NAME VARCHAR(15) PRIMARY KEY NOT NULL
);

CREATE TABLE GENDERS(
    NAME VARCHAR(10) PRIMARY KEY NOT NULL
);

CREATE TABLE YEARS(
    NUM INT PRIMARY KEY NOT NULL
);

CREATE TABLE LEGENDS(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    RACE_NAME VARCHAR(15) NOT NULL,
    GENDER_NAME VARCHAR(10) NOT NULL,
    YEAR_NUM INT NOT NULL,
    CONSTRAINT PK_LEGENDS PRIMARY KEY(ID),
    CONSTRAINT FK_LEGENDS_RACES FOREIGN KEY(RACE_NAME) REFERENCES RACES(NAME),
    CONSTRAINT FK_LEGENDS_GENDERS FOREIGN KEY(GENDERS_NAME) REFERENCES GENDERS(NAME),
    CONSTRAINT FK_LEGENDS_YEARS FOREIGN KEY(YEAR_NUM) REFERENCES YEARS(NUM),
    CONSTRAINT UNIQUE_NAME UNIQUE(NAME)
);

CREATE TABLE WEAPONS(
    NAME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_WEAPONS PRIMARY KEY(NAME)
);

CREATE TABLE LEGENDS_WEAPONS(
    LEGEND_ID INT NOT NULL,
    WEAPON_NAME VARCHAR(20),
    CONSTRAINT PK_LEGENDS_WEAPONS PRIMARY KEY(LEGEND_ID, WEAPON_NAME),
    CONSTRAINT FK_LEGENDS_WEAPONS_LEYEND FOREIGN KEY(LEGEND_ID) REFERENCES LEGENDS(ID),
    CONSTRAINT FK_LEGENDS_WEAPONS_WEAPON FOREIGN KEY(WEAPON_NAME) REFERENCES WEAPONS(NAME)
);

CREATE TABLE GAMES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LEGEND_ID INT NOT NULL,
    CONSTRAINT FK_GAMES_USERS FOREIGN KEY(LEGEND_ID) REFERENCES LEYENDS(ID)
);

CREATE TABLE ROLES(
  NAME VARCHAR(10) PRIMARY KEY NOT NULL
);

CREATE TABLE USERS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(80) NOT NULL,
    NICK VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    ROLE_NAME VARCHAR(10) NOT NULL,
    CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL),
    CONSTRAINT FK_ROLES_USERS FOREIGN KEY(ROL_NAME) REFERENCES ROLES(NAME)
);

CREATE TABLE GAMES_USERS(
    GAME_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    GUESSED INT,
    NUM_TRIES INT DEAFULT '0',
    CONSTRAINT PK_GAMES_USERS PRIMARY KEY(GAME_ID,USER_ID),
    CONSTRAINT FK_GAMES_GAMES_USERS FOREIGN KEY(GAME_ID) REFERENCES GAMES(ID),
    CONSTRAINT FK_USERS_GAMES_USERS FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE VIEW GAME_ALL AS 
SELECT GA.ID AS GAME_ID, 
    L.ID AS LEGEND_ID, 
    L.NAME AS LEGEND_NAME, 
    R.NAME AS RACE, 
    G.NAME AS GENDER, 
    Y.NUM AS YEAR, 
    GROUP_CONCAT(W.NAME, SEPARATOR ", ") AS WEAPONS
FROM LEGENDS AS L
    JOIN RACES AS R
    ON L.RACE_NAME = R.NAME
    JOIN GENDERS AS G
    ON L.GENDER_NAME = G.NAME
    JOIN YEARS AS Y
    ON L.YEAR_NUM = Y.NUM
    JOIN GAMES AS GA
    ON L.ID = GA.LEGEND_ID
    JOIN LEGENDS_WEAPONS AS LW
    ON L.ID = LW.LEGEND_ID
    JOIN WEAPONS AS W
    ON LW.WEAPON_NAME = W.NAME
GROUP BY GA.ID, L.ID, R.NAME, G.NAME, Y.NUM;
